site_name: Flaggen

nav:
  - Home: index.md
  - Development process:
    - development_process/workflow.md
    - development_process/pre_commit_pipeline.md
    - development_process/dagger_pipeline.md
  - Changelog: changelog.md

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - autorefs
  - mkdocstrings:
      watch:
        - flaggen/*
        - pipeline/*
        - CHANGELOG.md
        - README.md

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
