site_name: Fast feature flag
repo_url: https://github.com/GreNait/flaggen
repo_name: grenait/fastfeatureflag
edit_uri: edit/trunk/docs/

nav:
  - Home: index.md
  - Quickstart:
    - quickstart/quickstart_tldr.ipynb
    - quickstart/quickstart.md
  - Features:
    - features/feature_flag_code.ipynb
    - features/feature_flag_reference.md
    - features/shadow_code.ipynb
    - features/shadow_reference.md
    - features/configuration_code.ipynb
    - features/pytest_code.ipynb
    - features/pytest_code_reference.md
  - Usecases:
    - use_cases/broken_feature.ipynb
    - use_cases/unfinished_new_feature.ipynb
    - use_cases/refactor_feature.ipynb
  - roadmap.md
  - Changelog: changelog.md

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - header.autohide
    - navigation.footer
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - autorefs
  - mkdocs-jupyter:
      execute: true
      allow_errors: true
      include_source: True
  - mkdocstrings
  - git-revision-date-localized:
      enable_creation_date: true

watch:
  - fastfeatureflag
  - pipeline
  - CHANGELOG.md
  - README.md

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
