site_name: Flaggen
repo_url: https://github.com/GreNait/flaggen
repo_name: grenait/flaggen
edit_uri: edit/trunk/docs/

nav:
  - Home: index.md
  - quickstart.md
  - Development process:
    - development_process/workflow.md
    - development_process/pre_commit_pipeline.md
    - development_process/dagger_pipeline.md
  - features/features.md
  - Changelog: changelog.md

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - header.autohide
    - navigation.footer
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - autorefs
  - mkdocstrings
  - git-revision-date-localized:
      enable_creation_date: true

watch:
  - flaggen
  - pipeline
  - CHANGELOG.md
  - README.md

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
